In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('./reviews.csv')
data_sample = data.sample(frac = 1)

In [3]:
reviews = data_sample['Review']
labels = data_sample['Label'].fillna(0.)
reviews.head(10)
reviews.shape[0]

5914

In [4]:
reviews.loc[1300]

' Bạn bè bảo đi thử quán gia truyền nên đi Thề luôn chưa thấy quán bít tết nào tệ như điểm cũng dễ nhưng cầu thang di chuyển thì bé kiểu cổ ngày xưa bậc cao mà người đi phải lách Mình ngồi tầng nhưng nhìn chung chật nóng bàn kê san sát buổi tối mà đèn thì bật như kiểu tiết cảm tưởng như thời bao viên phục vụ Bàn người mà mang có đĩa dưa chuột bé gọi để hỏi thêm dưa chuột thì gọi mãi không thấy suất ăn của nó mới là quá kinh Mình gọi bánh mỳ chảo dăm bông trứng lòng đào thì mang cái chảo nhìn như đồ ăn trứng đến lòng trắng còn chảy nhão ra chưa thịt thì khô và Suất bít tết thì ngấy kinh một lượng mỡ ngập ngụa mà không có trứng cháy ở khoai tây lèo pate hộp nên cứng mà thịt bò thì dai thôi rồi cắt còn chẳng cắt hiểu vì sao quán vẫn khẩu vị tệ Thề không bao giờ quay trở'

In [5]:
# Loại bỏ kí tự đặc biệt và chuyển thành chữ cái viết thường
import re 

def preprocessor(text):
    """ Return a cleaned version of text
    """
    # Remove HTML markup
    text = re.sub('<[^>]*>', '', text)
    # Save emoticons for later appending
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    # Remove any non-word character and append the emoticons,
    # removing the nose character for standarization. Convert to lower case
    text = (re.sub('[\W]+', ' ', text.lower()) + ' ' + ' '.join(emoticons).replace('-', ' '))
    
    #Loại bỏ các chữ cái lặp nhau
    length = len(text)
    char = 0
    while char <length-1:
        if text[char] == text[char+1]:
            text = text[:char]+text[char+1:]
            #print(text)
            length-=1
            continue
        char+=1
    #loại bỏ số  và các chữ cái lạ:
    digits_and_characters = 'aăâbcdđeêfghijklmnoôơpqrstuưvxywzáàảãạắằẳẵặấầẩẫậéèẻẽẹếềểễệíìỉĩịóòỏõọốồổỗộớờởỡợúùủũụứừửữựýỳỷỹỵ(?::|;|=)(?:-)?(?:\)|\(|D|P) '
    text = ''.join([i for i in text if i in digits_and_characters])
    
    return text


In [6]:
print(preprocessor('ngoonnnnnnnn quáaaaaaa trời ơiiii oiiii <abcxyz> <345345345> |||| 12345맛있고'))

ngon quáa trời ơi oi  


In [7]:
# get rid of special characters and convert to lower case
for i in range (reviews.shape[0]):
    reviews.loc[i] = preprocessor(reviews.loc[i])
reviews.head(10)

/home/kaidn28/.local/lib/python3.6/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


1995     ở đó ăn rất cả cũng ăn được làm rất đam bảo n...
3980     ngồi chờ gọi đồ xog từ lúc kết quả ngồi đợi đ...
382      thích nhất sinh tố chuối dừa nếp lần nào đến ...
2235     a great place to drink and have fun wth your ...
4970                                            thích mê 
3942     only tried the here and i personaly think not...
4340     đc cái thương bánh mì thì còn ok chứ bánh ngọ...
3719                     chả hiểu nổi tiếng ngon ở cái j 
3101     mình hay ngồi ở hàng vị trí thuận tiện vì nằm...
1524     phát điên vì cái nhà hàng này quán nằm ngay t...
Name: Review, dtype: object

In [8]:
reviews.loc[1300]

' bạn bè bảo đi thử quán gia truyền nên đi thề luôn chưa thấy quán bít tết nào tệ như điểm cũng dễ nhưng cầu thang di chuyển thì bé kiểu cổ ngày xưa bậc cao mà người đi phải lách mình ngồi tầng nhưng nhìn chung chật nóng bàn kê san sát buổi tối mà đèn thì bật như kiểu tiết cảm tưởng như thời bao viên phục vụ bàn người mà mang có đĩa dưa chuột bé gọi để hỏi thêm dưa chuột thì gọi mãi không thấy suất ăn của nó mới là quá kinh mình gọi bánh mỳ chảo dăm bông trứng lòng đào thì mang cái chảo nhìn như đồ ăn trứng đến lòng trắng còn chảy nhão ra chưa thịt thì khô và suất bít tết thì ngấy kinh một lượng mỡ ngập ngụa mà không có trứng cháy ở khoai tây lèo pate hộp nên cứng mà thịt bò thì dai thôi rồi cắt còn chẳng cắt hiểu vì sao quán vẫn khẩu vị tệ thề không bao giờ quay trở '

In [9]:
from pyvi import ViTokenizer
for i in range (reviews.shape[0]):
    reviews.loc[i] = ViTokenizer.tokenize(reviews.loc[i]).replace('_','')
    

/home/kaidn28/.local/lib/python3.6/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


In [10]:
print(reviews.loc[1300], labels.loc[1300])

bạnbè bảo đi thử quán giatruyền nên đi thề luôn chưa thấy quán bít tết nào tệ như điểm cũng dễ nhưng cầuthang dichuyển thì bé kiểu cổ ngàyxưa bậc cao mà người đi phải lách mình ngồi tầng nhưng nhìnchung chật nóng bàn kê sansát buổi tối mà đèn thì bật như kiểu tiết cảmtưởng như thời baoviên phụcvụ bàn người mà mang có đĩa dưachuột bé gọi để hỏi thêm dưachuột thì gọi mãi không thấy suất ăn của nó mới là quá kinh mình gọi bánh mỳ chảo dăm bông trứng lòngđào thì mang cái chảo nhìn như đồ ăn trứng đến lòngtrắng còn chảy nhão ra chưa thịt thì khô và suất bít tết thì ngấy kinh một lượng mỡ ngậpngụa mà không có trứng cháy ở khoaitây lèo pate hộp nên cứng mà thịt bò thì dai thôi rồi cắt còn chẳng cắt hiểu vì sao quán vẫn khẩuvị tệ thề không baogiờ quay trở -1.0


In [11]:
from collections import Counter

vocab = Counter()
for twit in reviews:
    for word in twit.split(' '):
        vocab[word] += 1

vocab.most_common(10)

[('mình', 8885),
 ('ăn', 8838),
 ('là', 7168),
 ('thì', 7050),
 ('có', 6845),
 ('và', 5857),
 ('không', 5175),
 ('cũng', 4739),
 ('quán', 4706),
 ('rất', 3730)]

In [12]:
with open('./stopwords_vn.txt') as f:
    stopwords_vn = f.read().splitlines()
stopwords_vn[:10]

['alô', 'aha', 'ai', 'aiai', 'ainấy', 'aiđó', 'alô', 'amen', 'anh', 'anhấy']

In [13]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/kaidn28/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [14]:
from nltk.corpus import stopwords
stopwords_eng = stopwords.words('english')

In [15]:
stopwords = stopwords_vn + stopwords_eng

In [16]:
vocab_reduced = Counter()
# Go through all of the items of vocab using vocab.items() and pick only words that are not in 'stop_words' 
# and save them in vocab_reduced
for w, c in vocab.items():
    if not w in stopwords:
        vocab_reduced[w]=c

vocab_reduced.most_common(10)

[('không', 5175),
 ('quán', 4706),
 ('mà', 3635),
 ('lại', 3096),
 ('đồ', 3058),
 ('ngon', 2912),
 ('đi', 2856),
 ('ko', 2676),
 ('gọi', 2564),
 ('nhânviên', 2364)]

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer(stop_words = stopwords)
bag = bow.fit_transform(reviews)
print(bow.get_feature_names())

['ab', 'abc', 'abd', 'able', 'ac', 'ace', 'achi', 'acount', 'acountant', 'acoustic', 'actualy', 'ad', 'adamame', 'adayroi', 'ading', 'admin', 'adres', 'advertise', 'ae', 'aen', 'aeon', 'afogato', 'afordable', 'afternon', 'ag', 'ah', 'ahihi', 'ahip', 'ahuhu', 'aibảo', 'ailại', 'aingờ', 'aiu', 'aiyu', 'aiđời', 'ak', 'aka', 'al', 'alacart', 'alacarte', 'alarcarte', 'album', 'ale', 'alfres', 'alfresco', 'alfreso', 'alfrseco', 'alike', 'alisa', 'alisan', 'almaz', 'almost', 'alo', 'alone', 'along', 'alright', 'also', 'always', 'amazed', 'amazing', 'amhiểu', 'amore', 'amount', 'amounts', 'ampid', 'ample', 'andi', 'angel', 'angelina', 'anhchị', 'anhchịem', 'anhem', 'anhemem', 'anhvũ', 'anhđào', 'anoying', 'antoàn', 'antâm', 'anw', 'anyway', 'anủi', 'ao', 'aots', 'aozora', 'ap', 'apertizer', 'aple', 'arangement', 'area', 'aroi', 'around', 'art', 'arất', 'asam', 'asian', 'ask', 'asked', 'ate', 'atentive', 'atmosphere', 'atp', 'atvstp', 'australia', 'auth', 'authentic', 'available', 'avalon', 'av

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words = stopwords)
# Feed the tf-idf Vectorizer with twits using fit_transform()
tfidf_vec = tfidf.fit_transform(reviews)

# Formatting the number to 2 digits after the decimal point by showing on this notebook
np.set_printoptions(precision=2)
# To print array in one line
np.set_printoptions(linewidth=np.inf)
print(tfidf.get_feature_names())
print(tfidf_vec.toarray())

['ab', 'abc', 'abd', 'able', 'ac', 'ace', 'achi', 'acount', 'acountant', 'acoustic', 'actualy', 'ad', 'adamame', 'adayroi', 'ading', 'admin', 'adres', 'advertise', 'ae', 'aen', 'aeon', 'afogato', 'afordable', 'afternon', 'ag', 'ah', 'ahihi', 'ahip', 'ahuhu', 'aibảo', 'ailại', 'aingờ', 'aiu', 'aiyu', 'aiđời', 'ak', 'aka', 'al', 'alacart', 'alacarte', 'alarcarte', 'album', 'ale', 'alfres', 'alfresco', 'alfreso', 'alfrseco', 'alike', 'alisa', 'alisan', 'almaz', 'almost', 'alo', 'alone', 'along', 'alright', 'also', 'always', 'amazed', 'amazing', 'amhiểu', 'amore', 'amount', 'amounts', 'ampid', 'ample', 'andi', 'angel', 'angelina', 'anhchị', 'anhchịem', 'anhem', 'anhemem', 'anhvũ', 'anhđào', 'anoying', 'antoàn', 'antâm', 'anw', 'anyway', 'anủi', 'ao', 'aots', 'aozora', 'ap', 'apertizer', 'aple', 'arangement', 'area', 'aroi', 'around', 'art', 'arất', 'asam', 'asian', 'ask', 'asked', 'ate', 'atentive', 'atmosphere', 'atp', 'atvstp', 'australia', 'auth', 'authentic', 'available', 'avalon', 'av

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [19]:
tfidf_vec.shape

(5914, 11451)

In [20]:
bag.shape

(5914, 11451)

In [21]:
spliter = int(bag.shape[0]*0.8)
bag_train = bag[:spliter, :]
bag_test = bag[spliter:, :]
tfidf_train = tfidf_vec[:spliter,:]
tfidf_test = tfidf_vec[spliter:, :]
labels_train = labels[:spliter]
labels_test = labels[spliter:]

In [22]:
from sklearn.naive_bayes import MultinomialNB
nbc = MultinomialNB()

In [23]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [24]:
print(labels_train.isna().sum())

0


In [25]:
nbc.fit(bag_train.toarray(), labels_train)
labels_pred = nbc.predict(bag_test.toarray())

In [26]:
print(accuracy_score(labels_test, labels_pred))
print(f1_score(labels_test, labels_pred, average = 'macro'))

0.7489433643279797
0.5491317693979522


In [27]:
nbc.fit(tfidf_train.toarray(), labels_train)
labels_pred = nbc.predict(tfidf_test.toarray())

In [28]:
print(accuracy_score(labels_test, labels_pred))
print(f1_score(labels_test, labels_pred, average = 'macro'))

0.7531699070160609
0.5361749283001851


In [29]:
from sklearn.linear_model import LogisticRegression


In [30]:
lor = LogisticRegression()
lor.fit(bag_train.toarray(), labels_train)
labels_pred = lor.predict(bag_test.toarray())
print(accuracy_score(labels_test, labels_pred))
print(f1_score(labels_test, labels_pred, average = 'macro'))

0.727810650887574
0.5961274108492827


/home/kaidn28/.local/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [31]:
lor.fit(tfidf_train.toarray(), labels_train)
labels_pred = lor.predict(tfidf_test.toarray())
print(accuracy_score(labels_test, labels_pred))
print(f1_score(labels_test, labels_pred, average = 'macro'))

0.775993237531699
0.579863990417357


In [32]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(max_depth = None)

In [33]:
dtc.fit(bag_train.toarray(), labels_train)
labels_pred = dtc.predict(bag_test.toarray())
print(accuracy_score(labels_test, labels_pred))
print(f1_score(labels_test, labels_pred, average = 'macro'))

0.6136939983093829
0.49173622591344107


In [34]:
dtc.fit(tfidf_train.toarray(), labels_train)
labels_pred = dtc.predict(tfidf_test.toarray())
print(accuracy_score(labels_test, labels_pred))
print(f1_score(labels_test, labels_pred, average = 'macro'))

0.6027049873203719
0.4901840935921317


In [35]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(max_depth = None, random_state = 0)

In [36]:
rfc.fit(bag_train.toarray(), labels_train)
labels_pred = rfc.predict(bag_test.toarray())
print(accuracy_score(labels_test, labels_pred))
print(f1_score(labels_test, labels_pred, average = 'macro'))

0.7345731191885038
0.5428976418815631


In [37]:
rfc.fit(tfidf_train.toarray(), labels_train)
labels_pred = rfc.predict(tfidf_test.toarray())
print(accuracy_score(labels_test, labels_pred))
print(f1_score(labels_test, labels_pred, average = 'macro'))

0.746407438715131
0.5398185842499933


In [38]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier()